# CTest probes exercise the real tools, without a separate test framework.
cmake_minimum_required(VERSION 3.16)
get_filename_component(ROOT "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
set(CHECK "${ROOT}/scripts/memory_checks/check.sh")
if(NOT WORK)
  set(WORK "${CMAKE_CURRENT_BINARY_DIR}/memory-probes")
endif()
file(MAKE_DIRECTORY "${WORK}")
function(expect_result expected needle)
  execute_process(COMMAND ${ARGN} RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE errors)
  if((expected STREQUAL "pass" AND NOT status STREQUAL "0") OR
     (expected STREQUAL "fail" AND status STREQUAL "0") OR
     NOT "${output}${errors}" MATCHES "${needle}")
    message(FATAL_ERROR "Unexpected probe result ${status}: ${output}${errors}")
  endif()
endfunction()
if(MODE STREQUAL "sanitizers")
  expect_result(fail "AddressSanitizer: heap-buffer-overflow" "${PROBE}")
  expect_result(fail "runtime error: signed integer overflow" "${PROBE}" undefined)
elseif(MODE STREQUAL "stack")
  file(MAKE_DIRECTORY "${WORK}/build" "${WORK}/src")
  file(WRITE "${WORK}/src/probe.cpp" "// stack gate fixture\n")
  file(WRITE "${WORK}/budget.json" "{\"limit\":512,\"exceptions\":{},\"sources\":[\"src/probe.cpp\"]}")
  file(WRITE "${WORK}/build/memory-stack-manifest.json" "{\"probe.su\":\"src/probe.cpp\"}")
  file(WRITE "${WORK}/build/probe.su" "src/probe.cpp:1:1:void probe()\t32\tstatic\n")
  set(command bash "${CHECK}" stack "${WORK}/build" "${WORK}/budget.json" "${WORK}")
  expect_result(pass "stack records" ${command})
  file(WRITE "${WORK}/build/stale.su" "src/deleted.cpp:1:1:void old()\t9000\tstatic\n")
  expect_result(pass "stack records" ${command})
  file(WRITE "${WORK}/build/probe.su" "src/probe.cpp:1:1:void probe()\t513\tstatic\n")
  expect_result(fail "exceeds" ${command})
  file(WRITE "${WORK}/budget.json" "{\"limit\":512,\"exceptions\":{\"src/probe.cpp:void probe()\":513},\"sources\":[\"src/probe.cpp\"]}")
  expect_result(pass "stack records" ${command})
  file(WRITE "${WORK}/build/probe.su" "src/probe.cpp:1:1:void probe()\t514\tstatic\n")
  expect_result(fail "exceeds" ${command})
  file(WRITE "${WORK}/build/probe.su" "src/probe.cpp:1:1:void probe()\t16\tdynamic\n")
  expect_result(fail "unbounded" ${command})
  file(WRITE "${WORK}/build/probe.su" "broken report\n")
  expect_result(fail "Malformed" ${command})
  file(REMOVE "${WORK}/build/probe.su")
  expect_result(fail "Missing" ${command})
  file(WRITE "${WORK}/build/other.su" "src/other.cpp:1:1:void other()\t16\tstatic\n")
  file(WRITE "${WORK}/build/memory-stack-manifest.json" "{\"other.su\":\"src/other.cpp\"}")
  expect_result(fail "Missing stack instrumentation" ${command})
elseif(MODE STREQUAL "ram")
  expect_result(pass "RAM bytes" bash "${CHECK}" ram "${ELF}" "${ENVIRONMENT}")
  execute_process(COMMAND jq --arg env "${ENVIRONMENT}" ".[\$env].limits.dram = 0"
    "${ROOT}/scripts/memory_checks/static-ram-budgets.json"
    RESULT_VARIABLE status OUTPUT_VARIABLE budgets)
  if(NOT status STREQUAL "0")
    message(FATAL_ERROR "Cannot construct RAM rejection probe")
  endif()
  file(WRITE "${WORK}/budget.json" "${budgets}")
  expect_result(fail "exceeds" bash "${CHECK}" ram "${ELF}" "${ENVIRONMENT}" "${WORK}/budget.json")
elseif(MODE STREQUAL "tidy")
  file(WRITE "${WORK}/probe.cpp" "unsigned long size(int* p) { return sizeof(p)/sizeof(p[0]); }\nlong product(int a,int b) { return a*b; }\nint dangling() { int* p=new int(7); delete p; return *p; }\n")
  execute_process(COMMAND "${TOOL}" "${WORK}/probe.cpp" "--config={}"
    "--checks=-*,bugprone-sizeof-expression,bugprone-implicit-widening-of-multiplication-result,clang-analyzer-cplusplus.NewDelete"
    "--warnings-as-errors=*" -- -std=c++20
    RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE errors)
  foreach(check sizeof-expression implicit-widening-of-multiplication-result cplusplus.NewDelete)
    if(status STREQUAL "0" OR NOT "${output}${errors}" MATCHES "${check}")
      message(FATAL_ERROR "clang-tidy did not reject ${check}: ${output}${errors}")
    endif()
  endforeach()
else()
  message(FATAL_ERROR "Unknown memory probe MODE=${MODE}")
endif()
message(STATUS "${MODE} probes passed")
